// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestdetail"
)

// RequestDetailUpdate is the builder for updating RequestDetail entities.
type RequestDetailUpdate struct {
	config
	hooks    []Hook
	mutation *RequestDetailMutation
}

// Where appends a list predicates to the RequestDetailUpdate builder.
func (_u *RequestDetailUpdate) Where(ps ...predicate.RequestDetail) *RequestDetailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestDetailUpdate) SetRequestID(v string) *RequestDetailUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableRequestID(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RequestDetailUpdate) SetCompletedAt(v time.Time) *RequestDetailUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableCompletedAt(v *time.Time) *RequestDetailUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *RequestDetailUpdate) ClearCompletedAt() *RequestDetailUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestDetailUpdate) SetDurationMs(v int) *RequestDetailUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableDurationMs(v *int) *RequestDetailUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestDetailUpdate) AddDurationMs(v int) *RequestDetailUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestDetailUpdate) ClearDurationMs() *RequestDetailUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestDetailUpdate) SetStatusCode(v int) *RequestDetailUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableStatusCode(v *int) *RequestDetailUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestDetailUpdate) AddStatusCode(v int) *RequestDetailUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetSuccess sets the "success" field.
func (_u *RequestDetailUpdate) SetSuccess(v bool) *RequestDetailUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableSuccess(v *bool) *RequestDetailUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RequestDetailUpdate) SetPlatform(v string) *RequestDetailUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillablePlatform(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *RequestDetailUpdate) SetEndpoint(v string) *RequestDetailUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableEndpoint(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_u *RequestDetailUpdate) SetUpstreamEndpoint(v string) *RequestDetailUpdate {
	_u.mutation.SetUpstreamEndpoint(v)
	return _u
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableUpstreamEndpoint(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetUpstreamEndpoint(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestDetailUpdate) SetModel(v string) *RequestDetailUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableModel(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *RequestDetailUpdate) SetUpstreamModel(v string) *RequestDetailUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableUpstreamModel(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestDetailUpdate) SetStream(v bool) *RequestDetailUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableStream(v *bool) *RequestDetailUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RequestDetailUpdate) SetUserID(v int64) *RequestDetailUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableUserID(v *int64) *RequestDetailUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RequestDetailUpdate) AddUserID(v int64) *RequestDetailUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *RequestDetailUpdate) ClearUserID() *RequestDetailUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestDetailUpdate) SetAPIKeyID(v int64) *RequestDetailUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableAPIKeyID(v *int64) *RequestDetailUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *RequestDetailUpdate) AddAPIKeyID(v int64) *RequestDetailUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *RequestDetailUpdate) ClearAPIKeyID() *RequestDetailUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *RequestDetailUpdate) SetAccountID(v int64) *RequestDetailUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableAccountID(v *int64) *RequestDetailUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *RequestDetailUpdate) AddAccountID(v int64) *RequestDetailUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *RequestDetailUpdate) ClearAccountID() *RequestDetailUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RequestDetailUpdate) SetGroupID(v int64) *RequestDetailUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableGroupID(v *int64) *RequestDetailUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RequestDetailUpdate) AddGroupID(v int64) *RequestDetailUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RequestDetailUpdate) ClearGroupID() *RequestDetailUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *RequestDetailUpdate) SetSubscriptionID(v int64) *RequestDetailUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableSubscriptionID(v *int64) *RequestDetailUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *RequestDetailUpdate) AddSubscriptionID(v int64) *RequestDetailUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *RequestDetailUpdate) ClearSubscriptionID() *RequestDetailUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RequestDetailUpdate) SetIPAddress(v string) *RequestDetailUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableIPAddress(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RequestDetailUpdate) SetUserAgent(v string) *RequestDetailUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableUserAgent(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *RequestDetailUpdate) SetRequestHeaders(v map[string][]string) *RequestDetailUpdate {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *RequestDetailUpdate) SetResponseHeaders(v map[string][]string) *RequestDetailUpdate {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestDetailUpdate) SetRequestBody(v string) *RequestDetailUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableRequestBody(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (_u *RequestDetailUpdate) SetUpstreamRequestBody(v string) *RequestDetailUpdate {
	_u.mutation.SetUpstreamRequestBody(v)
	return _u
}

// SetNillableUpstreamRequestBody sets the "upstream_request_body" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableUpstreamRequestBody(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetUpstreamRequestBody(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestDetailUpdate) SetResponseBody(v string) *RequestDetailUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableResponseBody(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestDetailUpdate) SetErrorMessage(v string) *RequestDetailUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableErrorMessage(v *string) *RequestDetailUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetResponseTruncated sets the "response_truncated" field.
func (_u *RequestDetailUpdate) SetResponseTruncated(v bool) *RequestDetailUpdate {
	_u.mutation.SetResponseTruncated(v)
	return _u
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_u *RequestDetailUpdate) SetNillableResponseTruncated(v *bool) *RequestDetailUpdate {
	if v != nil {
		_u.SetResponseTruncated(*v)
	}
	return _u
}

// Mutation returns the RequestDetailMutation object of the builder.
func (_u *RequestDetailUpdate) Mutation() *RequestDetailMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestDetailUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestDetailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestDetailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestDetailUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestdetail.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := requestdetail.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := requestdetail.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamEndpoint(); ok {
		if err := requestdetail.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.upstream_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestdetail.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := requestdetail.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := requestdetail.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := requestdetail.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestDetailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestdetail.Table, requestdetail.Columns, sqlgraph.NewFieldSpec(requestdetail.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestdetail.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(requestdetail.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(requestdetail.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestdetail.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestdetail.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestdetail.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestdetail.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestdetail.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(requestdetail.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(requestdetail.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(requestdetail.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(requestdetail.FieldUpstreamEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestdetail.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(requestdetail.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestdetail.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(requestdetail.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(requestdetail.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(requestdetail.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(requestdetail.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(requestdetail.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(requestdetail.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(requestdetail.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(requestdetail.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(requestdetail.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(requestdetail.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(requestdetail.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(requestdetail.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(requestdetail.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(requestdetail.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(requestdetail.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(requestdetail.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(requestdetail.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(requestdetail.FieldRequestHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(requestdetail.FieldResponseHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestdetail.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestBody(); ok {
		_spec.SetField(requestdetail.FieldUpstreamRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestdetail.FieldResponseBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestdetail.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseTruncated(); ok {
		_spec.SetField(requestdetail.FieldResponseTruncated, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestDetailUpdateOne is the builder for updating a single RequestDetail entity.
type RequestDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestDetailMutation
}

// SetRequestID sets the "request_id" field.
func (_u *RequestDetailUpdateOne) SetRequestID(v string) *RequestDetailUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableRequestID(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RequestDetailUpdateOne) SetCompletedAt(v time.Time) *RequestDetailUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableCompletedAt(v *time.Time) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *RequestDetailUpdateOne) ClearCompletedAt() *RequestDetailUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestDetailUpdateOne) SetDurationMs(v int) *RequestDetailUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableDurationMs(v *int) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestDetailUpdateOne) AddDurationMs(v int) *RequestDetailUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestDetailUpdateOne) ClearDurationMs() *RequestDetailUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestDetailUpdateOne) SetStatusCode(v int) *RequestDetailUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableStatusCode(v *int) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestDetailUpdateOne) AddStatusCode(v int) *RequestDetailUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetSuccess sets the "success" field.
func (_u *RequestDetailUpdateOne) SetSuccess(v bool) *RequestDetailUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableSuccess(v *bool) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RequestDetailUpdateOne) SetPlatform(v string) *RequestDetailUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillablePlatform(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *RequestDetailUpdateOne) SetEndpoint(v string) *RequestDetailUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableEndpoint(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_u *RequestDetailUpdateOne) SetUpstreamEndpoint(v string) *RequestDetailUpdateOne {
	_u.mutation.SetUpstreamEndpoint(v)
	return _u
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableUpstreamEndpoint(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamEndpoint(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestDetailUpdateOne) SetModel(v string) *RequestDetailUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableModel(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *RequestDetailUpdateOne) SetUpstreamModel(v string) *RequestDetailUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableUpstreamModel(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestDetailUpdateOne) SetStream(v bool) *RequestDetailUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableStream(v *bool) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RequestDetailUpdateOne) SetUserID(v int64) *RequestDetailUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableUserID(v *int64) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RequestDetailUpdateOne) AddUserID(v int64) *RequestDetailUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *RequestDetailUpdateOne) ClearUserID() *RequestDetailUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestDetailUpdateOne) SetAPIKeyID(v int64) *RequestDetailUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableAPIKeyID(v *int64) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *RequestDetailUpdateOne) AddAPIKeyID(v int64) *RequestDetailUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *RequestDetailUpdateOne) ClearAPIKeyID() *RequestDetailUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *RequestDetailUpdateOne) SetAccountID(v int64) *RequestDetailUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableAccountID(v *int64) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *RequestDetailUpdateOne) AddAccountID(v int64) *RequestDetailUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *RequestDetailUpdateOne) ClearAccountID() *RequestDetailUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RequestDetailUpdateOne) SetGroupID(v int64) *RequestDetailUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableGroupID(v *int64) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *RequestDetailUpdateOne) AddGroupID(v int64) *RequestDetailUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RequestDetailUpdateOne) ClearGroupID() *RequestDetailUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *RequestDetailUpdateOne) SetSubscriptionID(v int64) *RequestDetailUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableSubscriptionID(v *int64) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *RequestDetailUpdateOne) AddSubscriptionID(v int64) *RequestDetailUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *RequestDetailUpdateOne) ClearSubscriptionID() *RequestDetailUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RequestDetailUpdateOne) SetIPAddress(v string) *RequestDetailUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableIPAddress(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RequestDetailUpdateOne) SetUserAgent(v string) *RequestDetailUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableUserAgent(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *RequestDetailUpdateOne) SetRequestHeaders(v map[string][]string) *RequestDetailUpdateOne {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *RequestDetailUpdateOne) SetResponseHeaders(v map[string][]string) *RequestDetailUpdateOne {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestDetailUpdateOne) SetRequestBody(v string) *RequestDetailUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableRequestBody(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (_u *RequestDetailUpdateOne) SetUpstreamRequestBody(v string) *RequestDetailUpdateOne {
	_u.mutation.SetUpstreamRequestBody(v)
	return _u
}

// SetNillableUpstreamRequestBody sets the "upstream_request_body" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableUpstreamRequestBody(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestBody(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestDetailUpdateOne) SetResponseBody(v string) *RequestDetailUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableResponseBody(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestDetailUpdateOne) SetErrorMessage(v string) *RequestDetailUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableErrorMessage(v *string) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetResponseTruncated sets the "response_truncated" field.
func (_u *RequestDetailUpdateOne) SetResponseTruncated(v bool) *RequestDetailUpdateOne {
	_u.mutation.SetResponseTruncated(v)
	return _u
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_u *RequestDetailUpdateOne) SetNillableResponseTruncated(v *bool) *RequestDetailUpdateOne {
	if v != nil {
		_u.SetResponseTruncated(*v)
	}
	return _u
}

// Mutation returns the RequestDetailMutation object of the builder.
func (_u *RequestDetailUpdateOne) Mutation() *RequestDetailMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestDetailUpdate builder.
func (_u *RequestDetailUpdateOne) Where(ps ...predicate.RequestDetail) *RequestDetailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestDetailUpdateOne) Select(field string, fields ...string) *RequestDetailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestDetail entity.
func (_u *RequestDetailUpdateOne) Save(ctx context.Context) (*RequestDetail, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestDetailUpdateOne) SaveX(ctx context.Context) *RequestDetail {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestDetailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestDetailUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestdetail.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := requestdetail.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := requestdetail.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamEndpoint(); ok {
		if err := requestdetail.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.upstream_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestdetail.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := requestdetail.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := requestdetail.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := requestdetail.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestDetailUpdateOne) sqlSave(ctx context.Context) (_node *RequestDetail, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestdetail.Table, requestdetail.Columns, sqlgraph.NewFieldSpec(requestdetail.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestdetail.FieldID)
		for _, f := range fields {
			if !requestdetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestdetail.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(requestdetail.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(requestdetail.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestdetail.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestdetail.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestdetail.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestdetail.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestdetail.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(requestdetail.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(requestdetail.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(requestdetail.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(requestdetail.FieldUpstreamEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestdetail.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(requestdetail.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestdetail.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(requestdetail.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(requestdetail.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(requestdetail.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(requestdetail.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(requestdetail.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(requestdetail.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(requestdetail.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(requestdetail.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(requestdetail.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(requestdetail.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(requestdetail.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(requestdetail.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(requestdetail.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(requestdetail.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(requestdetail.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(requestdetail.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(requestdetail.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(requestdetail.FieldRequestHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(requestdetail.FieldResponseHeaders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestdetail.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestBody(); ok {
		_spec.SetField(requestdetail.FieldUpstreamRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestdetail.FieldResponseBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestdetail.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseTruncated(); ok {
		_spec.SetField(requestdetail.FieldResponseTruncated, field.TypeBool, value)
	}
	_node = &RequestDetail{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
