// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestdetailimageartifact"
)

// RequestDetailImageArtifactUpdate is the builder for updating RequestDetailImageArtifact entities.
type RequestDetailImageArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *RequestDetailImageArtifactMutation
}

// Where appends a list predicates to the RequestDetailImageArtifactUpdate builder.
func (_u *RequestDetailImageArtifactUpdate) Where(ps ...predicate.RequestDetailImageArtifact) *RequestDetailImageArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestDetailImageArtifactUpdate) SetRequestID(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableRequestID(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *RequestDetailImageArtifactUpdate) SetDirection(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableDirection(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RequestDetailImageArtifactUpdate) SetSource(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableSource(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestDetailImageArtifactUpdate) SetStatus(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableStatus(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *RequestDetailImageArtifactUpdate) SetS3Key(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableS3Key(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// SetOriginalURL sets the "original_url" field.
func (_u *RequestDetailImageArtifactUpdate) SetOriginalURL(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetOriginalURL(v)
	return _u
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableOriginalURL(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetOriginalURL(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *RequestDetailImageArtifactUpdate) SetContentType(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableContentType(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *RequestDetailImageArtifactUpdate) SetFileName(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableFileName(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *RequestDetailImageArtifactUpdate) SetSizeBytes(v int64) *RequestDetailImageArtifactUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableSizeBytes(v *int64) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *RequestDetailImageArtifactUpdate) AddSizeBytes(v int64) *RequestDetailImageArtifactUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *RequestDetailImageArtifactUpdate) SetSha256(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableSha256(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetImageIndex sets the "image_index" field.
func (_u *RequestDetailImageArtifactUpdate) SetImageIndex(v int) *RequestDetailImageArtifactUpdate {
	_u.mutation.ResetImageIndex()
	_u.mutation.SetImageIndex(v)
	return _u
}

// SetNillableImageIndex sets the "image_index" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableImageIndex(v *int) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetImageIndex(*v)
	}
	return _u
}

// AddImageIndex adds value to the "image_index" field.
func (_u *RequestDetailImageArtifactUpdate) AddImageIndex(v int) *RequestDetailImageArtifactUpdate {
	_u.mutation.AddImageIndex(v)
	return _u
}

// ClearImageIndex clears the value of the "image_index" field.
func (_u *RequestDetailImageArtifactUpdate) ClearImageIndex() *RequestDetailImageArtifactUpdate {
	_u.mutation.ClearImageIndex()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RequestDetailImageArtifactUpdate) SetMetadata(v map[string]interface{}) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestDetailImageArtifactUpdate) SetErrorMessage(v string) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdate) SetNillableErrorMessage(v *string) *RequestDetailImageArtifactUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestDetailImageArtifactUpdate) SetUpdatedAt(v time.Time) *RequestDetailImageArtifactUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RequestDetailImageArtifactMutation object of the builder.
func (_u *RequestDetailImageArtifactUpdate) Mutation() *RequestDetailImageArtifactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestDetailImageArtifactUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestDetailImageArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestDetailImageArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestDetailImageArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestDetailImageArtifactUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestdetailimageartifact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestDetailImageArtifactUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestdetailimageartifact.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := requestdetailimageartifact.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := requestdetailimageartifact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestdetailimageartifact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := requestdetailimageartifact.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := requestdetailimageartifact.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := requestdetailimageartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestDetailImageArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestdetailimageartifact.Table, requestdetailimageartifact.Columns, sqlgraph.NewFieldSpec(requestdetailimageartifact.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestdetailimageartifact.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(requestdetailimageartifact.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestdetailimageartifact.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(requestdetailimageartifact.FieldS3Key, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalURL(); ok {
		_spec.SetField(requestdetailimageartifact.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(requestdetailimageartifact.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(requestdetailimageartifact.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(requestdetailimageartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageIndex(); ok {
		_spec.SetField(requestdetailimageartifact.FieldImageIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageIndex(); ok {
		_spec.AddField(requestdetailimageartifact.FieldImageIndex, field.TypeInt, value)
	}
	if _u.mutation.ImageIndexCleared() {
		_spec.ClearField(requestdetailimageartifact.FieldImageIndex, field.TypeInt)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(requestdetailimageartifact.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestdetailimageartifact.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestdetailimageartifact.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestdetailimageartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestDetailImageArtifactUpdateOne is the builder for updating a single RequestDetailImageArtifact entity.
type RequestDetailImageArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestDetailImageArtifactMutation
}

// SetRequestID sets the "request_id" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetRequestID(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableRequestID(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetDirection(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableDirection(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetSource(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableSource(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetStatus(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableStatus(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetS3Key(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableS3Key(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// SetOriginalURL sets the "original_url" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetOriginalURL(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetOriginalURL(v)
	return _u
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableOriginalURL(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetOriginalURL(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetContentType(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableContentType(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetFileName(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableFileName(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetSizeBytes(v int64) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableSizeBytes(v *int64) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *RequestDetailImageArtifactUpdateOne) AddSizeBytes(v int64) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetSha256(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableSha256(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetImageIndex sets the "image_index" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetImageIndex(v int) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.ResetImageIndex()
	_u.mutation.SetImageIndex(v)
	return _u
}

// SetNillableImageIndex sets the "image_index" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableImageIndex(v *int) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetImageIndex(*v)
	}
	return _u
}

// AddImageIndex adds value to the "image_index" field.
func (_u *RequestDetailImageArtifactUpdateOne) AddImageIndex(v int) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.AddImageIndex(v)
	return _u
}

// ClearImageIndex clears the value of the "image_index" field.
func (_u *RequestDetailImageArtifactUpdateOne) ClearImageIndex() *RequestDetailImageArtifactUpdateOne {
	_u.mutation.ClearImageIndex()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetMetadata(v map[string]interface{}) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetErrorMessage(v string) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestDetailImageArtifactUpdateOne) SetNillableErrorMessage(v *string) *RequestDetailImageArtifactUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestDetailImageArtifactUpdateOne) SetUpdatedAt(v time.Time) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RequestDetailImageArtifactMutation object of the builder.
func (_u *RequestDetailImageArtifactUpdateOne) Mutation() *RequestDetailImageArtifactMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestDetailImageArtifactUpdate builder.
func (_u *RequestDetailImageArtifactUpdateOne) Where(ps ...predicate.RequestDetailImageArtifact) *RequestDetailImageArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestDetailImageArtifactUpdateOne) Select(field string, fields ...string) *RequestDetailImageArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestDetailImageArtifact entity.
func (_u *RequestDetailImageArtifactUpdateOne) Save(ctx context.Context) (*RequestDetailImageArtifact, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestDetailImageArtifactUpdateOne) SaveX(ctx context.Context) *RequestDetailImageArtifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestDetailImageArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestDetailImageArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestDetailImageArtifactUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestdetailimageartifact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestDetailImageArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestdetailimageartifact.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := requestdetailimageartifact.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := requestdetailimageartifact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestdetailimageartifact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := requestdetailimageartifact.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := requestdetailimageartifact.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := requestdetailimageartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestDetailImageArtifactUpdateOne) sqlSave(ctx context.Context) (_node *RequestDetailImageArtifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestdetailimageartifact.Table, requestdetailimageartifact.Columns, sqlgraph.NewFieldSpec(requestdetailimageartifact.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestDetailImageArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestdetailimageartifact.FieldID)
		for _, f := range fields {
			if !requestdetailimageartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestdetailimageartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestdetailimageartifact.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(requestdetailimageartifact.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestdetailimageartifact.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(requestdetailimageartifact.FieldS3Key, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalURL(); ok {
		_spec.SetField(requestdetailimageartifact.FieldOriginalURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(requestdetailimageartifact.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(requestdetailimageartifact.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(requestdetailimageartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageIndex(); ok {
		_spec.SetField(requestdetailimageartifact.FieldImageIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageIndex(); ok {
		_spec.AddField(requestdetailimageartifact.FieldImageIndex, field.TypeInt, value)
	}
	if _u.mutation.ImageIndexCleared() {
		_spec.ClearField(requestdetailimageartifact.FieldImageIndex, field.TypeInt)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(requestdetailimageartifact.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestdetailimageartifact.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestdetailimageartifact.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RequestDetailImageArtifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestdetailimageartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
