// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/requestdetailimageartifact"
)

// RequestDetailImageArtifact is the model entity for the RequestDetailImageArtifact schema.
type RequestDetailImageArtifact struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction string `json:"direction,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// S3Key holds the value of the "s3_key" field.
	S3Key string `json:"s3_key,omitempty"`
	// OriginalURL holds the value of the "original_url" field.
	OriginalURL string `json:"original_url,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// ImageIndex holds the value of the "image_index" field.
	ImageIndex *int `json:"image_index,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestDetailImageArtifact) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestdetailimageartifact.FieldMetadata:
			values[i] = new([]byte)
		case requestdetailimageartifact.FieldID, requestdetailimageartifact.FieldSizeBytes, requestdetailimageartifact.FieldImageIndex:
			values[i] = new(sql.NullInt64)
		case requestdetailimageartifact.FieldRequestID, requestdetailimageartifact.FieldDirection, requestdetailimageartifact.FieldSource, requestdetailimageartifact.FieldStatus, requestdetailimageartifact.FieldS3Key, requestdetailimageartifact.FieldOriginalURL, requestdetailimageartifact.FieldContentType, requestdetailimageartifact.FieldFileName, requestdetailimageartifact.FieldSha256, requestdetailimageartifact.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case requestdetailimageartifact.FieldCreatedAt, requestdetailimageartifact.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestDetailImageArtifact fields.
func (_m *RequestDetailImageArtifact) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestdetailimageartifact.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case requestdetailimageartifact.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case requestdetailimageartifact.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				_m.Direction = value.String
			}
		case requestdetailimageartifact.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case requestdetailimageartifact.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case requestdetailimageartifact.FieldS3Key:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_key", values[i])
			} else if value.Valid {
				_m.S3Key = value.String
			}
		case requestdetailimageartifact.FieldOriginalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_url", values[i])
			} else if value.Valid {
				_m.OriginalURL = value.String
			}
		case requestdetailimageartifact.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case requestdetailimageartifact.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case requestdetailimageartifact.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case requestdetailimageartifact.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case requestdetailimageartifact.FieldImageIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_index", values[i])
			} else if value.Valid {
				_m.ImageIndex = new(int)
				*_m.ImageIndex = int(value.Int64)
			}
		case requestdetailimageartifact.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case requestdetailimageartifact.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case requestdetailimageartifact.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requestdetailimageartifact.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestDetailImageArtifact.
// This includes values selected through modifiers, order, etc.
func (_m *RequestDetailImageArtifact) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequestDetailImageArtifact.
// Note that you need to call RequestDetailImageArtifact.Unwrap() before calling this method if this RequestDetailImageArtifact
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestDetailImageArtifact) Update() *RequestDetailImageArtifactUpdateOne {
	return NewRequestDetailImageArtifactClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestDetailImageArtifact entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestDetailImageArtifact) Unwrap() *RequestDetailImageArtifact {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestDetailImageArtifact is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestDetailImageArtifact) String() string {
	var builder strings.Builder
	builder.WriteString("RequestDetailImageArtifact(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(_m.Direction)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("s3_key=")
	builder.WriteString(_m.S3Key)
	builder.WriteString(", ")
	builder.WriteString("original_url=")
	builder.WriteString(_m.OriginalURL)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	if v := _m.ImageIndex; v != nil {
		builder.WriteString("image_index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestDetailImageArtifacts is a parsable slice of RequestDetailImageArtifact.
type RequestDetailImageArtifacts []*RequestDetailImageArtifact
