// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/requestdetailimageartifact"
)

// RequestDetailImageArtifactCreate is the builder for creating a RequestDetailImageArtifact entity.
type RequestDetailImageArtifactCreate struct {
	config
	mutation *RequestDetailImageArtifactMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *RequestDetailImageArtifactCreate) SetRequestID(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetDirection sets the "direction" field.
func (_c *RequestDetailImageArtifactCreate) SetDirection(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableDirection(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetDirection(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *RequestDetailImageArtifactCreate) SetSource(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableSource(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RequestDetailImageArtifactCreate) SetStatus(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableStatus(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetS3Key sets the "s3_key" field.
func (_c *RequestDetailImageArtifactCreate) SetS3Key(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetS3Key(v)
	return _c
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableS3Key(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetS3Key(*v)
	}
	return _c
}

// SetOriginalURL sets the "original_url" field.
func (_c *RequestDetailImageArtifactCreate) SetOriginalURL(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetOriginalURL(v)
	return _c
}

// SetNillableOriginalURL sets the "original_url" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableOriginalURL(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetOriginalURL(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *RequestDetailImageArtifactCreate) SetContentType(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableContentType(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *RequestDetailImageArtifactCreate) SetFileName(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableFileName(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *RequestDetailImageArtifactCreate) SetSizeBytes(v int64) *RequestDetailImageArtifactCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableSizeBytes(v *int64) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *RequestDetailImageArtifactCreate) SetSha256(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableSha256(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetSha256(*v)
	}
	return _c
}

// SetImageIndex sets the "image_index" field.
func (_c *RequestDetailImageArtifactCreate) SetImageIndex(v int) *RequestDetailImageArtifactCreate {
	_c.mutation.SetImageIndex(v)
	return _c
}

// SetNillableImageIndex sets the "image_index" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableImageIndex(v *int) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetImageIndex(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RequestDetailImageArtifactCreate) SetMetadata(v map[string]interface{}) *RequestDetailImageArtifactCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RequestDetailImageArtifactCreate) SetErrorMessage(v string) *RequestDetailImageArtifactCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableErrorMessage(v *string) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestDetailImageArtifactCreate) SetCreatedAt(v time.Time) *RequestDetailImageArtifactCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableCreatedAt(v *time.Time) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestDetailImageArtifactCreate) SetUpdatedAt(v time.Time) *RequestDetailImageArtifactCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestDetailImageArtifactCreate) SetNillableUpdatedAt(v *time.Time) *RequestDetailImageArtifactCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RequestDetailImageArtifactMutation object of the builder.
func (_c *RequestDetailImageArtifactCreate) Mutation() *RequestDetailImageArtifactMutation {
	return _c.mutation
}

// Save creates the RequestDetailImageArtifact in the database.
func (_c *RequestDetailImageArtifactCreate) Save(ctx context.Context) (*RequestDetailImageArtifact, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestDetailImageArtifactCreate) SaveX(ctx context.Context) *RequestDetailImageArtifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestDetailImageArtifactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestDetailImageArtifactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestDetailImageArtifactCreate) defaults() {
	if _, ok := _c.mutation.Direction(); !ok {
		v := requestdetailimageartifact.DefaultDirection
		_c.mutation.SetDirection(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := requestdetailimageartifact.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := requestdetailimageartifact.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.S3Key(); !ok {
		v := requestdetailimageartifact.DefaultS3Key
		_c.mutation.SetS3Key(v)
	}
	if _, ok := _c.mutation.OriginalURL(); !ok {
		v := requestdetailimageartifact.DefaultOriginalURL
		_c.mutation.SetOriginalURL(v)
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		v := requestdetailimageartifact.DefaultContentType
		_c.mutation.SetContentType(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := requestdetailimageartifact.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := requestdetailimageartifact.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		v := requestdetailimageartifact.DefaultSha256
		_c.mutation.SetSha256(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := requestdetailimageartifact.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := requestdetailimageartifact.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestdetailimageartifact.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := requestdetailimageartifact.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestDetailImageArtifactCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := requestdetailimageartifact.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := requestdetailimageartifact.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := requestdetailimageartifact.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := requestdetailimageartifact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.S3Key(); !ok {
		return &ValidationError{Name: "s3_key", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.s3_key"`)}
	}
	if _, ok := _c.mutation.OriginalURL(); !ok {
		return &ValidationError{Name: "original_url", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.original_url"`)}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := requestdetailimageartifact.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := requestdetailimageartifact.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.size_bytes"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := requestdetailimageartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "RequestDetailImageArtifact.sha256": %w`, err)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.Metadata(); !ok {
			return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.metadata"`)}
		}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.error_message"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RequestDetailImageArtifact.updated_at"`)}
	}
	return nil
}

func (_c *RequestDetailImageArtifactCreate) sqlSave(ctx context.Context) (*RequestDetailImageArtifact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestDetailImageArtifactCreate) createSpec() (*RequestDetailImageArtifact, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestDetailImageArtifact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestdetailimageartifact.Table, sqlgraph.NewFieldSpec(requestdetailimageartifact.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(requestdetailimageartifact.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(requestdetailimageartifact.FieldDirection, field.TypeString, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(requestdetailimageartifact.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.S3Key(); ok {
		_spec.SetField(requestdetailimageartifact.FieldS3Key, field.TypeString, value)
		_node.S3Key = value
	}
	if value, ok := _c.mutation.OriginalURL(); ok {
		_spec.SetField(requestdetailimageartifact.FieldOriginalURL, field.TypeString, value)
		_node.OriginalURL = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(requestdetailimageartifact.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(requestdetailimageartifact.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(requestdetailimageartifact.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.ImageIndex(); ok {
		_spec.SetField(requestdetailimageartifact.FieldImageIndex, field.TypeInt, value)
		_node.ImageIndex = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(requestdetailimageartifact.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(requestdetailimageartifact.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestdetailimageartifact.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requestdetailimageartifact.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestDetailImageArtifact.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestDetailImageArtifactUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestDetailImageArtifactCreate) OnConflict(opts ...sql.ConflictOption) *RequestDetailImageArtifactUpsertOne {
	_c.conflict = opts
	return &RequestDetailImageArtifactUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestDetailImageArtifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestDetailImageArtifactCreate) OnConflictColumns(columns ...string) *RequestDetailImageArtifactUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestDetailImageArtifactUpsertOne{
		create: _c,
	}
}

type (
	// RequestDetailImageArtifactUpsertOne is the builder for "upsert"-ing
	//  one RequestDetailImageArtifact node.
	RequestDetailImageArtifactUpsertOne struct {
		create *RequestDetailImageArtifactCreate
	}

	// RequestDetailImageArtifactUpsert is the "OnConflict" setter.
	RequestDetailImageArtifactUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *RequestDetailImageArtifactUpsert) SetRequestID(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateRequestID() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldRequestID)
	return u
}

// SetDirection sets the "direction" field.
func (u *RequestDetailImageArtifactUpsert) SetDirection(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldDirection, v)
	return u
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateDirection() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldDirection)
	return u
}

// SetSource sets the "source" field.
func (u *RequestDetailImageArtifactUpsert) SetSource(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateSource() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldSource)
	return u
}

// SetStatus sets the "status" field.
func (u *RequestDetailImageArtifactUpsert) SetStatus(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateStatus() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldStatus)
	return u
}

// SetS3Key sets the "s3_key" field.
func (u *RequestDetailImageArtifactUpsert) SetS3Key(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldS3Key, v)
	return u
}

// UpdateS3Key sets the "s3_key" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateS3Key() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldS3Key)
	return u
}

// SetOriginalURL sets the "original_url" field.
func (u *RequestDetailImageArtifactUpsert) SetOriginalURL(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldOriginalURL, v)
	return u
}

// UpdateOriginalURL sets the "original_url" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateOriginalURL() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldOriginalURL)
	return u
}

// SetContentType sets the "content_type" field.
func (u *RequestDetailImageArtifactUpsert) SetContentType(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateContentType() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldContentType)
	return u
}

// SetFileName sets the "file_name" field.
func (u *RequestDetailImageArtifactUpsert) SetFileName(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateFileName() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldFileName)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *RequestDetailImageArtifactUpsert) SetSizeBytes(v int64) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateSizeBytes() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *RequestDetailImageArtifactUpsert) AddSizeBytes(v int64) *RequestDetailImageArtifactUpsert {
	u.Add(requestdetailimageartifact.FieldSizeBytes, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *RequestDetailImageArtifactUpsert) SetSha256(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateSha256() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldSha256)
	return u
}

// SetImageIndex sets the "image_index" field.
func (u *RequestDetailImageArtifactUpsert) SetImageIndex(v int) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldImageIndex, v)
	return u
}

// UpdateImageIndex sets the "image_index" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateImageIndex() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldImageIndex)
	return u
}

// AddImageIndex adds v to the "image_index" field.
func (u *RequestDetailImageArtifactUpsert) AddImageIndex(v int) *RequestDetailImageArtifactUpsert {
	u.Add(requestdetailimageartifact.FieldImageIndex, v)
	return u
}

// ClearImageIndex clears the value of the "image_index" field.
func (u *RequestDetailImageArtifactUpsert) ClearImageIndex() *RequestDetailImageArtifactUpsert {
	u.SetNull(requestdetailimageartifact.FieldImageIndex)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *RequestDetailImageArtifactUpsert) SetMetadata(v map[string]interface{}) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateMetadata() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldMetadata)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestDetailImageArtifactUpsert) SetErrorMessage(v string) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateErrorMessage() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldErrorMessage)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestDetailImageArtifactUpsert) SetUpdatedAt(v time.Time) *RequestDetailImageArtifactUpsert {
	u.Set(requestdetailimageartifact.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsert) UpdateUpdatedAt() *RequestDetailImageArtifactUpsert {
	u.SetExcluded(requestdetailimageartifact.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestDetailImageArtifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestDetailImageArtifactUpsertOne) UpdateNewValues() *RequestDetailImageArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestdetailimageartifact.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestDetailImageArtifact.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestDetailImageArtifactUpsertOne) Ignore() *RequestDetailImageArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestDetailImageArtifactUpsertOne) DoNothing() *RequestDetailImageArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestDetailImageArtifactCreate.OnConflict
// documentation for more info.
func (u *RequestDetailImageArtifactUpsertOne) Update(set func(*RequestDetailImageArtifactUpsert)) *RequestDetailImageArtifactUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestDetailImageArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestDetailImageArtifactUpsertOne) SetRequestID(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateRequestID() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateRequestID()
	})
}

// SetDirection sets the "direction" field.
func (u *RequestDetailImageArtifactUpsertOne) SetDirection(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateDirection() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateDirection()
	})
}

// SetSource sets the "source" field.
func (u *RequestDetailImageArtifactUpsertOne) SetSource(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateSource() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateSource()
	})
}

// SetStatus sets the "status" field.
func (u *RequestDetailImageArtifactUpsertOne) SetStatus(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateStatus() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateStatus()
	})
}

// SetS3Key sets the "s3_key" field.
func (u *RequestDetailImageArtifactUpsertOne) SetS3Key(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetS3Key(v)
	})
}

// UpdateS3Key sets the "s3_key" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateS3Key() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateS3Key()
	})
}

// SetOriginalURL sets the "original_url" field.
func (u *RequestDetailImageArtifactUpsertOne) SetOriginalURL(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetOriginalURL(v)
	})
}

// UpdateOriginalURL sets the "original_url" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateOriginalURL() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateOriginalURL()
	})
}

// SetContentType sets the "content_type" field.
func (u *RequestDetailImageArtifactUpsertOne) SetContentType(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateContentType() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateContentType()
	})
}

// SetFileName sets the "file_name" field.
func (u *RequestDetailImageArtifactUpsertOne) SetFileName(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateFileName() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateFileName()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *RequestDetailImageArtifactUpsertOne) SetSizeBytes(v int64) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *RequestDetailImageArtifactUpsertOne) AddSizeBytes(v int64) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateSizeBytes() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *RequestDetailImageArtifactUpsertOne) SetSha256(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateSha256() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateSha256()
	})
}

// SetImageIndex sets the "image_index" field.
func (u *RequestDetailImageArtifactUpsertOne) SetImageIndex(v int) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetImageIndex(v)
	})
}

// AddImageIndex adds v to the "image_index" field.
func (u *RequestDetailImageArtifactUpsertOne) AddImageIndex(v int) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.AddImageIndex(v)
	})
}

// UpdateImageIndex sets the "image_index" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateImageIndex() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateImageIndex()
	})
}

// ClearImageIndex clears the value of the "image_index" field.
func (u *RequestDetailImageArtifactUpsertOne) ClearImageIndex() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.ClearImageIndex()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RequestDetailImageArtifactUpsertOne) SetMetadata(v map[string]interface{}) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateMetadata() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateMetadata()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestDetailImageArtifactUpsertOne) SetErrorMessage(v string) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateErrorMessage() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestDetailImageArtifactUpsertOne) SetUpdatedAt(v time.Time) *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertOne) UpdateUpdatedAt() *RequestDetailImageArtifactUpsertOne {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RequestDetailImageArtifactUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestDetailImageArtifactCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestDetailImageArtifactUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestDetailImageArtifactUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestDetailImageArtifactUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestDetailImageArtifactCreateBulk is the builder for creating many RequestDetailImageArtifact entities in bulk.
type RequestDetailImageArtifactCreateBulk struct {
	config
	err      error
	builders []*RequestDetailImageArtifactCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestDetailImageArtifact entities in the database.
func (_c *RequestDetailImageArtifactCreateBulk) Save(ctx context.Context) ([]*RequestDetailImageArtifact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestDetailImageArtifact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestDetailImageArtifactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestDetailImageArtifactCreateBulk) SaveX(ctx context.Context) []*RequestDetailImageArtifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestDetailImageArtifactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestDetailImageArtifactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestDetailImageArtifact.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestDetailImageArtifactUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestDetailImageArtifactCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestDetailImageArtifactUpsertBulk {
	_c.conflict = opts
	return &RequestDetailImageArtifactUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestDetailImageArtifact.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestDetailImageArtifactCreateBulk) OnConflictColumns(columns ...string) *RequestDetailImageArtifactUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestDetailImageArtifactUpsertBulk{
		create: _c,
	}
}

// RequestDetailImageArtifactUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestDetailImageArtifact nodes.
type RequestDetailImageArtifactUpsertBulk struct {
	create *RequestDetailImageArtifactCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestDetailImageArtifact.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestDetailImageArtifactUpsertBulk) UpdateNewValues() *RequestDetailImageArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestdetailimageartifact.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestDetailImageArtifact.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestDetailImageArtifactUpsertBulk) Ignore() *RequestDetailImageArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestDetailImageArtifactUpsertBulk) DoNothing() *RequestDetailImageArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestDetailImageArtifactCreateBulk.OnConflict
// documentation for more info.
func (u *RequestDetailImageArtifactUpsertBulk) Update(set func(*RequestDetailImageArtifactUpsert)) *RequestDetailImageArtifactUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestDetailImageArtifactUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetRequestID(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateRequestID() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateRequestID()
	})
}

// SetDirection sets the "direction" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetDirection(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateDirection() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateDirection()
	})
}

// SetSource sets the "source" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetSource(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateSource() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateSource()
	})
}

// SetStatus sets the "status" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetStatus(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateStatus() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateStatus()
	})
}

// SetS3Key sets the "s3_key" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetS3Key(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetS3Key(v)
	})
}

// UpdateS3Key sets the "s3_key" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateS3Key() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateS3Key()
	})
}

// SetOriginalURL sets the "original_url" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetOriginalURL(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetOriginalURL(v)
	})
}

// UpdateOriginalURL sets the "original_url" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateOriginalURL() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateOriginalURL()
	})
}

// SetContentType sets the "content_type" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetContentType(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateContentType() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateContentType()
	})
}

// SetFileName sets the "file_name" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetFileName(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateFileName() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateFileName()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetSizeBytes(v int64) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *RequestDetailImageArtifactUpsertBulk) AddSizeBytes(v int64) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateSizeBytes() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetSha256(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateSha256() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateSha256()
	})
}

// SetImageIndex sets the "image_index" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetImageIndex(v int) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetImageIndex(v)
	})
}

// AddImageIndex adds v to the "image_index" field.
func (u *RequestDetailImageArtifactUpsertBulk) AddImageIndex(v int) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.AddImageIndex(v)
	})
}

// UpdateImageIndex sets the "image_index" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateImageIndex() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateImageIndex()
	})
}

// ClearImageIndex clears the value of the "image_index" field.
func (u *RequestDetailImageArtifactUpsertBulk) ClearImageIndex() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.ClearImageIndex()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetMetadata(v map[string]interface{}) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateMetadata() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateMetadata()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetErrorMessage(v string) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateErrorMessage() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestDetailImageArtifactUpsertBulk) SetUpdatedAt(v time.Time) *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestDetailImageArtifactUpsertBulk) UpdateUpdatedAt() *RequestDetailImageArtifactUpsertBulk {
	return u.Update(func(s *RequestDetailImageArtifactUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RequestDetailImageArtifactUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestDetailImageArtifactCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestDetailImageArtifactCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestDetailImageArtifactUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
