// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/requestdetail"
)

// RequestDetailCreate is the builder for creating a RequestDetail entity.
type RequestDetailCreate struct {
	config
	mutation *RequestDetailMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *RequestDetailCreate) SetRequestID(v string) *RequestDetailCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestDetailCreate) SetCreatedAt(v time.Time) *RequestDetailCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableCreatedAt(v *time.Time) *RequestDetailCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *RequestDetailCreate) SetCompletedAt(v time.Time) *RequestDetailCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableCompletedAt(v *time.Time) *RequestDetailCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RequestDetailCreate) SetDurationMs(v int) *RequestDetailCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableDurationMs(v *int) *RequestDetailCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *RequestDetailCreate) SetStatusCode(v int) *RequestDetailCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableStatusCode(v *int) *RequestDetailCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *RequestDetailCreate) SetSuccess(v bool) *RequestDetailCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableSuccess(v *bool) *RequestDetailCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *RequestDetailCreate) SetPlatform(v string) *RequestDetailCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillablePlatform(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *RequestDetailCreate) SetEndpoint(v string) *RequestDetailCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableEndpoint(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_c *RequestDetailCreate) SetUpstreamEndpoint(v string) *RequestDetailCreate {
	_c.mutation.SetUpstreamEndpoint(v)
	return _c
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableUpstreamEndpoint(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetUpstreamEndpoint(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *RequestDetailCreate) SetModel(v string) *RequestDetailCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableModel(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *RequestDetailCreate) SetUpstreamModel(v string) *RequestDetailCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableUpstreamModel(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *RequestDetailCreate) SetStream(v bool) *RequestDetailCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableStream(v *bool) *RequestDetailCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RequestDetailCreate) SetUserID(v int64) *RequestDetailCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableUserID(v *int64) *RequestDetailCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *RequestDetailCreate) SetAPIKeyID(v int64) *RequestDetailCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableAPIKeyID(v *int64) *RequestDetailCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *RequestDetailCreate) SetAccountID(v int64) *RequestDetailCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableAccountID(v *int64) *RequestDetailCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *RequestDetailCreate) SetGroupID(v int64) *RequestDetailCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableGroupID(v *int64) *RequestDetailCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *RequestDetailCreate) SetSubscriptionID(v int64) *RequestDetailCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableSubscriptionID(v *int64) *RequestDetailCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *RequestDetailCreate) SetIPAddress(v string) *RequestDetailCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableIPAddress(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *RequestDetailCreate) SetUserAgent(v string) *RequestDetailCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableUserAgent(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetRequestHeaders sets the "request_headers" field.
func (_c *RequestDetailCreate) SetRequestHeaders(v map[string][]string) *RequestDetailCreate {
	_c.mutation.SetRequestHeaders(v)
	return _c
}

// SetResponseHeaders sets the "response_headers" field.
func (_c *RequestDetailCreate) SetResponseHeaders(v map[string][]string) *RequestDetailCreate {
	_c.mutation.SetResponseHeaders(v)
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RequestDetailCreate) SetRequestBody(v string) *RequestDetailCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableRequestBody(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (_c *RequestDetailCreate) SetUpstreamRequestBody(v string) *RequestDetailCreate {
	_c.mutation.SetUpstreamRequestBody(v)
	return _c
}

// SetNillableUpstreamRequestBody sets the "upstream_request_body" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableUpstreamRequestBody(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetUpstreamRequestBody(*v)
	}
	return _c
}

// SetResponseContent sets the "response_content" field.
func (_c *RequestDetailCreate) SetResponseContent(v string) *RequestDetailCreate {
	_c.mutation.SetResponseContent(v)
	return _c
}

// SetNillableResponseContent sets the "response_content" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableResponseContent(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetResponseContent(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RequestDetailCreate) SetResponseBody(v string) *RequestDetailCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableResponseBody(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RequestDetailCreate) SetErrorMessage(v string) *RequestDetailCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableErrorMessage(v *string) *RequestDetailCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetResponseTruncated sets the "response_truncated" field.
func (_c *RequestDetailCreate) SetResponseTruncated(v bool) *RequestDetailCreate {
	_c.mutation.SetResponseTruncated(v)
	return _c
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_c *RequestDetailCreate) SetNillableResponseTruncated(v *bool) *RequestDetailCreate {
	if v != nil {
		_c.SetResponseTruncated(*v)
	}
	return _c
}

// Mutation returns the RequestDetailMutation object of the builder.
func (_c *RequestDetailCreate) Mutation() *RequestDetailMutation {
	return _c.mutation
}

// Save creates the RequestDetail in the database.
func (_c *RequestDetailCreate) Save(ctx context.Context) (*RequestDetail, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestDetailCreate) SaveX(ctx context.Context) *RequestDetail {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestDetailCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestDetailCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestDetailCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestdetail.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := requestdetail.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := requestdetail.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := requestdetail.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		v := requestdetail.DefaultEndpoint
		_c.mutation.SetEndpoint(v)
	}
	if _, ok := _c.mutation.UpstreamEndpoint(); !ok {
		v := requestdetail.DefaultUpstreamEndpoint
		_c.mutation.SetUpstreamEndpoint(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := requestdetail.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := requestdetail.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := requestdetail.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		v := requestdetail.DefaultIPAddress
		_c.mutation.SetIPAddress(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := requestdetail.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		v := requestdetail.DefaultRequestHeaders
		_c.mutation.SetRequestHeaders(v)
	}
	if _, ok := _c.mutation.ResponseHeaders(); !ok {
		v := requestdetail.DefaultResponseHeaders
		_c.mutation.SetResponseHeaders(v)
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		v := requestdetail.DefaultRequestBody
		_c.mutation.SetRequestBody(v)
	}
	if _, ok := _c.mutation.UpstreamRequestBody(); !ok {
		v := requestdetail.DefaultUpstreamRequestBody
		_c.mutation.SetUpstreamRequestBody(v)
	}
	if _, ok := _c.mutation.ResponseContent(); !ok {
		v := requestdetail.DefaultResponseContent
		_c.mutation.SetResponseContent(v)
	}
	if _, ok := _c.mutation.ResponseBody(); !ok {
		v := requestdetail.DefaultResponseBody
		_c.mutation.SetResponseBody(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := requestdetail.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.ResponseTruncated(); !ok {
		v := requestdetail.DefaultResponseTruncated
		_c.mutation.SetResponseTruncated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestDetailCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestDetail.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := requestdetail.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestDetail.created_at"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "RequestDetail.status_code"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "RequestDetail.success"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "RequestDetail.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := requestdetail.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "RequestDetail.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := requestdetail.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamEndpoint(); !ok {
		return &ValidationError{Name: "upstream_endpoint", err: errors.New(`ent: missing required field "RequestDetail.upstream_endpoint"`)}
	}
	if v, ok := _c.mutation.UpstreamEndpoint(); ok {
		if err := requestdetail.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.upstream_endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "RequestDetail.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := requestdetail.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "RequestDetail.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := requestdetail.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "RequestDetail.stream"`)}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "RequestDetail.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := requestdetail.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "RequestDetail.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := requestdetail.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestDetail.user_agent": %w`, err)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.RequestHeaders(); !ok {
			return &ValidationError{Name: "request_headers", err: errors.New(`ent: missing required field "RequestDetail.request_headers"`)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.ResponseHeaders(); !ok {
			return &ValidationError{Name: "response_headers", err: errors.New(`ent: missing required field "RequestDetail.response_headers"`)}
		}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "RequestDetail.request_body"`)}
	}
	if _, ok := _c.mutation.UpstreamRequestBody(); !ok {
		return &ValidationError{Name: "upstream_request_body", err: errors.New(`ent: missing required field "RequestDetail.upstream_request_body"`)}
	}
	if _, ok := _c.mutation.ResponseContent(); !ok {
		return &ValidationError{Name: "response_content", err: errors.New(`ent: missing required field "RequestDetail.response_content"`)}
	}
	if _, ok := _c.mutation.ResponseBody(); !ok {
		return &ValidationError{Name: "response_body", err: errors.New(`ent: missing required field "RequestDetail.response_body"`)}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "RequestDetail.error_message"`)}
	}
	if _, ok := _c.mutation.ResponseTruncated(); !ok {
		return &ValidationError{Name: "response_truncated", err: errors.New(`ent: missing required field "RequestDetail.response_truncated"`)}
	}
	return nil
}

func (_c *RequestDetailCreate) sqlSave(ctx context.Context) (*RequestDetail, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestDetailCreate) createSpec() (*RequestDetail, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestDetail{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestdetail.Table, sqlgraph.NewFieldSpec(requestdetail.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(requestdetail.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestdetail.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(requestdetail.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(requestdetail.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(requestdetail.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(requestdetail.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(requestdetail.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(requestdetail.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(requestdetail.FieldUpstreamEndpoint, field.TypeString, value)
		_node.UpstreamEndpoint = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(requestdetail.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(requestdetail.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(requestdetail.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(requestdetail.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(requestdetail.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(requestdetail.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(requestdetail.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(requestdetail.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(requestdetail.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(requestdetail.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.RequestHeaders(); ok {
		_spec.SetField(requestdetail.FieldRequestHeaders, field.TypeJSON, value)
		_node.RequestHeaders = value
	}
	if value, ok := _c.mutation.ResponseHeaders(); ok {
		_spec.SetField(requestdetail.FieldResponseHeaders, field.TypeJSON, value)
		_node.ResponseHeaders = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(requestdetail.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.UpstreamRequestBody(); ok {
		_spec.SetField(requestdetail.FieldUpstreamRequestBody, field.TypeString, value)
		_node.UpstreamRequestBody = value
	}
	if value, ok := _c.mutation.ResponseContent(); ok {
		_spec.SetField(requestdetail.FieldResponseContent, field.TypeString, value)
		_node.ResponseContent = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(requestdetail.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(requestdetail.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.ResponseTruncated(); ok {
		_spec.SetField(requestdetail.FieldResponseTruncated, field.TypeBool, value)
		_node.ResponseTruncated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestDetail.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestDetailUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestDetailCreate) OnConflict(opts ...sql.ConflictOption) *RequestDetailUpsertOne {
	_c.conflict = opts
	return &RequestDetailUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestDetailCreate) OnConflictColumns(columns ...string) *RequestDetailUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestDetailUpsertOne{
		create: _c,
	}
}

type (
	// RequestDetailUpsertOne is the builder for "upsert"-ing
	//  one RequestDetail node.
	RequestDetailUpsertOne struct {
		create *RequestDetailCreate
	}

	// RequestDetailUpsert is the "OnConflict" setter.
	RequestDetailUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *RequestDetailUpsert) SetRequestID(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateRequestID() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldRequestID)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *RequestDetailUpsert) SetCompletedAt(v time.Time) *RequestDetailUpsert {
	u.Set(requestdetail.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateCompletedAt() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RequestDetailUpsert) ClearCompletedAt() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldCompletedAt)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestDetailUpsert) SetDurationMs(v int) *RequestDetailUpsert {
	u.Set(requestdetail.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateDurationMs() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestDetailUpsert) AddDurationMs(v int) *RequestDetailUpsert {
	u.Add(requestdetail.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestDetailUpsert) ClearDurationMs() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldDurationMs)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *RequestDetailUpsert) SetStatusCode(v int) *RequestDetailUpsert {
	u.Set(requestdetail.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateStatusCode() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestDetailUpsert) AddStatusCode(v int) *RequestDetailUpsert {
	u.Add(requestdetail.FieldStatusCode, v)
	return u
}

// SetSuccess sets the "success" field.
func (u *RequestDetailUpsert) SetSuccess(v bool) *RequestDetailUpsert {
	u.Set(requestdetail.FieldSuccess, v)
	return u
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateSuccess() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldSuccess)
	return u
}

// SetPlatform sets the "platform" field.
func (u *RequestDetailUpsert) SetPlatform(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdatePlatform() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldPlatform)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *RequestDetailUpsert) SetEndpoint(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateEndpoint() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldEndpoint)
	return u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *RequestDetailUpsert) SetUpstreamEndpoint(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldUpstreamEndpoint, v)
	return u
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateUpstreamEndpoint() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldUpstreamEndpoint)
	return u
}

// SetModel sets the "model" field.
func (u *RequestDetailUpsert) SetModel(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateModel() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *RequestDetailUpsert) SetUpstreamModel(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateUpstreamModel() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldUpstreamModel)
	return u
}

// SetStream sets the "stream" field.
func (u *RequestDetailUpsert) SetStream(v bool) *RequestDetailUpsert {
	u.Set(requestdetail.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateStream() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldStream)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestDetailUpsert) SetUserID(v int64) *RequestDetailUpsert {
	u.Set(requestdetail.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateUserID() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *RequestDetailUpsert) AddUserID(v int64) *RequestDetailUpsert {
	u.Add(requestdetail.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *RequestDetailUpsert) ClearUserID() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestDetailUpsert) SetAPIKeyID(v int64) *RequestDetailUpsert {
	u.Set(requestdetail.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateAPIKeyID() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RequestDetailUpsert) AddAPIKeyID(v int64) *RequestDetailUpsert {
	u.Add(requestdetail.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *RequestDetailUpsert) ClearAPIKeyID() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldAPIKeyID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *RequestDetailUpsert) SetAccountID(v int64) *RequestDetailUpsert {
	u.Set(requestdetail.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateAccountID() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *RequestDetailUpsert) AddAccountID(v int64) *RequestDetailUpsert {
	u.Add(requestdetail.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *RequestDetailUpsert) ClearAccountID() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldAccountID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *RequestDetailUpsert) SetGroupID(v int64) *RequestDetailUpsert {
	u.Set(requestdetail.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateGroupID() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *RequestDetailUpsert) AddGroupID(v int64) *RequestDetailUpsert {
	u.Add(requestdetail.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestDetailUpsert) ClearGroupID() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldGroupID)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *RequestDetailUpsert) SetSubscriptionID(v int64) *RequestDetailUpsert {
	u.Set(requestdetail.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateSubscriptionID() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *RequestDetailUpsert) AddSubscriptionID(v int64) *RequestDetailUpsert {
	u.Add(requestdetail.FieldSubscriptionID, v)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *RequestDetailUpsert) ClearSubscriptionID() *RequestDetailUpsert {
	u.SetNull(requestdetail.FieldSubscriptionID)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestDetailUpsert) SetIPAddress(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateIPAddress() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldIPAddress)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestDetailUpsert) SetUserAgent(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateUserAgent() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldUserAgent)
	return u
}

// SetRequestHeaders sets the "request_headers" field.
func (u *RequestDetailUpsert) SetRequestHeaders(v map[string][]string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldRequestHeaders, v)
	return u
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateRequestHeaders() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldRequestHeaders)
	return u
}

// SetResponseHeaders sets the "response_headers" field.
func (u *RequestDetailUpsert) SetResponseHeaders(v map[string][]string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldResponseHeaders, v)
	return u
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateResponseHeaders() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldResponseHeaders)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *RequestDetailUpsert) SetRequestBody(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateRequestBody() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldRequestBody)
	return u
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (u *RequestDetailUpsert) SetUpstreamRequestBody(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldUpstreamRequestBody, v)
	return u
}

// UpdateUpstreamRequestBody sets the "upstream_request_body" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateUpstreamRequestBody() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldUpstreamRequestBody)
	return u
}

// SetResponseContent sets the "response_content" field.
func (u *RequestDetailUpsert) SetResponseContent(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldResponseContent, v)
	return u
}

// UpdateResponseContent sets the "response_content" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateResponseContent() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldResponseContent)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *RequestDetailUpsert) SetResponseBody(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateResponseBody() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldResponseBody)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestDetailUpsert) SetErrorMessage(v string) *RequestDetailUpsert {
	u.Set(requestdetail.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateErrorMessage() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldErrorMessage)
	return u
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *RequestDetailUpsert) SetResponseTruncated(v bool) *RequestDetailUpsert {
	u.Set(requestdetail.FieldResponseTruncated, v)
	return u
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *RequestDetailUpsert) UpdateResponseTruncated() *RequestDetailUpsert {
	u.SetExcluded(requestdetail.FieldResponseTruncated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestDetailUpsertOne) UpdateNewValues() *RequestDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestdetail.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestDetail.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestDetailUpsertOne) Ignore() *RequestDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestDetailUpsertOne) DoNothing() *RequestDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestDetailCreate.OnConflict
// documentation for more info.
func (u *RequestDetailUpsertOne) Update(set func(*RequestDetailUpsert)) *RequestDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestDetailUpsertOne) SetRequestID(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateRequestID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateRequestID()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RequestDetailUpsertOne) SetCompletedAt(v time.Time) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateCompletedAt() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RequestDetailUpsertOne) ClearCompletedAt() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearCompletedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestDetailUpsertOne) SetDurationMs(v int) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestDetailUpsertOne) AddDurationMs(v int) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateDurationMs() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestDetailUpsertOne) ClearDurationMs() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearDurationMs()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *RequestDetailUpsertOne) SetStatusCode(v int) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestDetailUpsertOne) AddStatusCode(v int) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateStatusCode() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateStatusCode()
	})
}

// SetSuccess sets the "success" field.
func (u *RequestDetailUpsertOne) SetSuccess(v bool) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateSuccess() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateSuccess()
	})
}

// SetPlatform sets the "platform" field.
func (u *RequestDetailUpsertOne) SetPlatform(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdatePlatform() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdatePlatform()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *RequestDetailUpsertOne) SetEndpoint(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateEndpoint() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateEndpoint()
	})
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *RequestDetailUpsertOne) SetUpstreamEndpoint(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUpstreamEndpoint(v)
	})
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateUpstreamEndpoint() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUpstreamEndpoint()
	})
}

// SetModel sets the "model" field.
func (u *RequestDetailUpsertOne) SetModel(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateModel() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *RequestDetailUpsertOne) SetUpstreamModel(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateUpstreamModel() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetStream sets the "stream" field.
func (u *RequestDetailUpsertOne) SetStream(v bool) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateStream() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateStream()
	})
}

// SetUserID sets the "user_id" field.
func (u *RequestDetailUpsertOne) SetUserID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RequestDetailUpsertOne) AddUserID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateUserID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *RequestDetailUpsertOne) ClearUserID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestDetailUpsertOne) SetAPIKeyID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RequestDetailUpsertOne) AddAPIKeyID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateAPIKeyID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *RequestDetailUpsertOne) ClearAPIKeyID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *RequestDetailUpsertOne) SetAccountID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *RequestDetailUpsertOne) AddAccountID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateAccountID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *RequestDetailUpsertOne) ClearAccountID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RequestDetailUpsertOne) SetGroupID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RequestDetailUpsertOne) AddGroupID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateGroupID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestDetailUpsertOne) ClearGroupID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *RequestDetailUpsertOne) SetSubscriptionID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *RequestDetailUpsertOne) AddSubscriptionID(v int64) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateSubscriptionID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *RequestDetailUpsertOne) ClearSubscriptionID() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestDetailUpsertOne) SetIPAddress(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateIPAddress() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestDetailUpsertOne) SetUserAgent(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateUserAgent() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUserAgent()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *RequestDetailUpsertOne) SetRequestHeaders(v map[string][]string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateRequestHeaders() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetResponseHeaders sets the "response_headers" field.
func (u *RequestDetailUpsertOne) SetResponseHeaders(v map[string][]string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseHeaders(v)
	})
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateResponseHeaders() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestDetailUpsertOne) SetRequestBody(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateRequestBody() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateRequestBody()
	})
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (u *RequestDetailUpsertOne) SetUpstreamRequestBody(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUpstreamRequestBody(v)
	})
}

// UpdateUpstreamRequestBody sets the "upstream_request_body" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateUpstreamRequestBody() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUpstreamRequestBody()
	})
}

// SetResponseContent sets the "response_content" field.
func (u *RequestDetailUpsertOne) SetResponseContent(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseContent(v)
	})
}

// UpdateResponseContent sets the "response_content" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateResponseContent() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseContent()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestDetailUpsertOne) SetResponseBody(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateResponseBody() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseBody()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestDetailUpsertOne) SetErrorMessage(v string) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateErrorMessage() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *RequestDetailUpsertOne) SetResponseTruncated(v bool) *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseTruncated(v)
	})
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *RequestDetailUpsertOne) UpdateResponseTruncated() *RequestDetailUpsertOne {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseTruncated()
	})
}

// Exec executes the query.
func (u *RequestDetailUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestDetailCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestDetailUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestDetailUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestDetailUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestDetailCreateBulk is the builder for creating many RequestDetail entities in bulk.
type RequestDetailCreateBulk struct {
	config
	err      error
	builders []*RequestDetailCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestDetail entities in the database.
func (_c *RequestDetailCreateBulk) Save(ctx context.Context) ([]*RequestDetail, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestDetail, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestDetailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestDetailCreateBulk) SaveX(ctx context.Context) []*RequestDetail {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestDetailCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestDetailCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestDetail.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestDetailUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestDetailCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestDetailUpsertBulk {
	_c.conflict = opts
	return &RequestDetailUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestDetailCreateBulk) OnConflictColumns(columns ...string) *RequestDetailUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestDetailUpsertBulk{
		create: _c,
	}
}

// RequestDetailUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestDetail nodes.
type RequestDetailUpsertBulk struct {
	create *RequestDetailCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestDetailUpsertBulk) UpdateNewValues() *RequestDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestdetail.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestDetail.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestDetailUpsertBulk) Ignore() *RequestDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestDetailUpsertBulk) DoNothing() *RequestDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestDetailCreateBulk.OnConflict
// documentation for more info.
func (u *RequestDetailUpsertBulk) Update(set func(*RequestDetailUpsert)) *RequestDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestDetailUpsertBulk) SetRequestID(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateRequestID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateRequestID()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RequestDetailUpsertBulk) SetCompletedAt(v time.Time) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateCompletedAt() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RequestDetailUpsertBulk) ClearCompletedAt() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearCompletedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestDetailUpsertBulk) SetDurationMs(v int) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestDetailUpsertBulk) AddDurationMs(v int) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateDurationMs() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestDetailUpsertBulk) ClearDurationMs() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearDurationMs()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *RequestDetailUpsertBulk) SetStatusCode(v int) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *RequestDetailUpsertBulk) AddStatusCode(v int) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateStatusCode() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateStatusCode()
	})
}

// SetSuccess sets the "success" field.
func (u *RequestDetailUpsertBulk) SetSuccess(v bool) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateSuccess() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateSuccess()
	})
}

// SetPlatform sets the "platform" field.
func (u *RequestDetailUpsertBulk) SetPlatform(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdatePlatform() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdatePlatform()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *RequestDetailUpsertBulk) SetEndpoint(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateEndpoint() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateEndpoint()
	})
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *RequestDetailUpsertBulk) SetUpstreamEndpoint(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUpstreamEndpoint(v)
	})
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateUpstreamEndpoint() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUpstreamEndpoint()
	})
}

// SetModel sets the "model" field.
func (u *RequestDetailUpsertBulk) SetModel(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateModel() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *RequestDetailUpsertBulk) SetUpstreamModel(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateUpstreamModel() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetStream sets the "stream" field.
func (u *RequestDetailUpsertBulk) SetStream(v bool) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateStream() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateStream()
	})
}

// SetUserID sets the "user_id" field.
func (u *RequestDetailUpsertBulk) SetUserID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RequestDetailUpsertBulk) AddUserID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateUserID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *RequestDetailUpsertBulk) ClearUserID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestDetailUpsertBulk) SetAPIKeyID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *RequestDetailUpsertBulk) AddAPIKeyID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateAPIKeyID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *RequestDetailUpsertBulk) ClearAPIKeyID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *RequestDetailUpsertBulk) SetAccountID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *RequestDetailUpsertBulk) AddAccountID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateAccountID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *RequestDetailUpsertBulk) ClearAccountID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RequestDetailUpsertBulk) SetGroupID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *RequestDetailUpsertBulk) AddGroupID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateGroupID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestDetailUpsertBulk) ClearGroupID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *RequestDetailUpsertBulk) SetSubscriptionID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *RequestDetailUpsertBulk) AddSubscriptionID(v int64) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateSubscriptionID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *RequestDetailUpsertBulk) ClearSubscriptionID() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestDetailUpsertBulk) SetIPAddress(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateIPAddress() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestDetailUpsertBulk) SetUserAgent(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateUserAgent() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUserAgent()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *RequestDetailUpsertBulk) SetRequestHeaders(v map[string][]string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateRequestHeaders() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetResponseHeaders sets the "response_headers" field.
func (u *RequestDetailUpsertBulk) SetResponseHeaders(v map[string][]string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseHeaders(v)
	})
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateResponseHeaders() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestDetailUpsertBulk) SetRequestBody(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateRequestBody() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateRequestBody()
	})
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (u *RequestDetailUpsertBulk) SetUpstreamRequestBody(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetUpstreamRequestBody(v)
	})
}

// UpdateUpstreamRequestBody sets the "upstream_request_body" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateUpstreamRequestBody() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateUpstreamRequestBody()
	})
}

// SetResponseContent sets the "response_content" field.
func (u *RequestDetailUpsertBulk) SetResponseContent(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseContent(v)
	})
}

// UpdateResponseContent sets the "response_content" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateResponseContent() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseContent()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestDetailUpsertBulk) SetResponseBody(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateResponseBody() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseBody()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestDetailUpsertBulk) SetErrorMessage(v string) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateErrorMessage() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *RequestDetailUpsertBulk) SetResponseTruncated(v bool) *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.SetResponseTruncated(v)
	})
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *RequestDetailUpsertBulk) UpdateResponseTruncated() *RequestDetailUpsertBulk {
	return u.Update(func(s *RequestDetailUpsert) {
		s.UpdateResponseTruncated()
	})
}

// Exec executes the query.
func (u *RequestDetailUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestDetailCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestDetailCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestDetailUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
