// Code generated by ent, DO NOT EDIT.

package requestdetailimageartifact

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldRequestID, v))
}

// Direction applies equality check predicate on the "direction" field. It's identical to DirectionEQ.
func Direction(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldDirection, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldSource, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldStatus, v))
}

// S3Key applies equality check predicate on the "s3_key" field. It's identical to S3KeyEQ.
func S3Key(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldS3Key, v))
}

// OriginalURL applies equality check predicate on the "original_url" field. It's identical to OriginalURLEQ.
func OriginalURL(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldOriginalURL, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldContentType, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldFileName, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldSizeBytes, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldSha256, v))
}

// ImageIndex applies equality check predicate on the "image_index" field. It's identical to ImageIndexEQ.
func ImageIndex(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldImageIndex, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldRequestID, v))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldDirection, vs...))
}

// DirectionGT applies the GT predicate on the "direction" field.
func DirectionGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldDirection, v))
}

// DirectionGTE applies the GTE predicate on the "direction" field.
func DirectionGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldDirection, v))
}

// DirectionLT applies the LT predicate on the "direction" field.
func DirectionLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldDirection, v))
}

// DirectionLTE applies the LTE predicate on the "direction" field.
func DirectionLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldDirection, v))
}

// DirectionContains applies the Contains predicate on the "direction" field.
func DirectionContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldDirection, v))
}

// DirectionHasPrefix applies the HasPrefix predicate on the "direction" field.
func DirectionHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldDirection, v))
}

// DirectionHasSuffix applies the HasSuffix predicate on the "direction" field.
func DirectionHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldDirection, v))
}

// DirectionEqualFold applies the EqualFold predicate on the "direction" field.
func DirectionEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldDirection, v))
}

// DirectionContainsFold applies the ContainsFold predicate on the "direction" field.
func DirectionContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldDirection, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldSource, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldStatus, v))
}

// S3KeyEQ applies the EQ predicate on the "s3_key" field.
func S3KeyEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldS3Key, v))
}

// S3KeyNEQ applies the NEQ predicate on the "s3_key" field.
func S3KeyNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldS3Key, v))
}

// S3KeyIn applies the In predicate on the "s3_key" field.
func S3KeyIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldS3Key, vs...))
}

// S3KeyNotIn applies the NotIn predicate on the "s3_key" field.
func S3KeyNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldS3Key, vs...))
}

// S3KeyGT applies the GT predicate on the "s3_key" field.
func S3KeyGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldS3Key, v))
}

// S3KeyGTE applies the GTE predicate on the "s3_key" field.
func S3KeyGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldS3Key, v))
}

// S3KeyLT applies the LT predicate on the "s3_key" field.
func S3KeyLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldS3Key, v))
}

// S3KeyLTE applies the LTE predicate on the "s3_key" field.
func S3KeyLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldS3Key, v))
}

// S3KeyContains applies the Contains predicate on the "s3_key" field.
func S3KeyContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldS3Key, v))
}

// S3KeyHasPrefix applies the HasPrefix predicate on the "s3_key" field.
func S3KeyHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldS3Key, v))
}

// S3KeyHasSuffix applies the HasSuffix predicate on the "s3_key" field.
func S3KeyHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldS3Key, v))
}

// S3KeyEqualFold applies the EqualFold predicate on the "s3_key" field.
func S3KeyEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldS3Key, v))
}

// S3KeyContainsFold applies the ContainsFold predicate on the "s3_key" field.
func S3KeyContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldS3Key, v))
}

// OriginalURLEQ applies the EQ predicate on the "original_url" field.
func OriginalURLEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldOriginalURL, v))
}

// OriginalURLNEQ applies the NEQ predicate on the "original_url" field.
func OriginalURLNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldOriginalURL, v))
}

// OriginalURLIn applies the In predicate on the "original_url" field.
func OriginalURLIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldOriginalURL, vs...))
}

// OriginalURLNotIn applies the NotIn predicate on the "original_url" field.
func OriginalURLNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldOriginalURL, vs...))
}

// OriginalURLGT applies the GT predicate on the "original_url" field.
func OriginalURLGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldOriginalURL, v))
}

// OriginalURLGTE applies the GTE predicate on the "original_url" field.
func OriginalURLGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldOriginalURL, v))
}

// OriginalURLLT applies the LT predicate on the "original_url" field.
func OriginalURLLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldOriginalURL, v))
}

// OriginalURLLTE applies the LTE predicate on the "original_url" field.
func OriginalURLLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldOriginalURL, v))
}

// OriginalURLContains applies the Contains predicate on the "original_url" field.
func OriginalURLContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldOriginalURL, v))
}

// OriginalURLHasPrefix applies the HasPrefix predicate on the "original_url" field.
func OriginalURLHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldOriginalURL, v))
}

// OriginalURLHasSuffix applies the HasSuffix predicate on the "original_url" field.
func OriginalURLHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldOriginalURL, v))
}

// OriginalURLEqualFold applies the EqualFold predicate on the "original_url" field.
func OriginalURLEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldOriginalURL, v))
}

// OriginalURLContainsFold applies the ContainsFold predicate on the "original_url" field.
func OriginalURLContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldOriginalURL, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldContentType, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldFileName, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldSizeBytes, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldSha256, v))
}

// ImageIndexEQ applies the EQ predicate on the "image_index" field.
func ImageIndexEQ(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldImageIndex, v))
}

// ImageIndexNEQ applies the NEQ predicate on the "image_index" field.
func ImageIndexNEQ(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldImageIndex, v))
}

// ImageIndexIn applies the In predicate on the "image_index" field.
func ImageIndexIn(vs ...int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldImageIndex, vs...))
}

// ImageIndexNotIn applies the NotIn predicate on the "image_index" field.
func ImageIndexNotIn(vs ...int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldImageIndex, vs...))
}

// ImageIndexGT applies the GT predicate on the "image_index" field.
func ImageIndexGT(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldImageIndex, v))
}

// ImageIndexGTE applies the GTE predicate on the "image_index" field.
func ImageIndexGTE(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldImageIndex, v))
}

// ImageIndexLT applies the LT predicate on the "image_index" field.
func ImageIndexLT(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldImageIndex, v))
}

// ImageIndexLTE applies the LTE predicate on the "image_index" field.
func ImageIndexLTE(v int) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldImageIndex, v))
}

// ImageIndexIsNil applies the IsNil predicate on the "image_index" field.
func ImageIndexIsNil() predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIsNull(FieldImageIndex))
}

// ImageIndexNotNil applies the NotNil predicate on the "image_index" field.
func ImageIndexNotNil() predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotNull(FieldImageIndex))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestDetailImageArtifact) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestDetailImageArtifact) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestDetailImageArtifact) predicate.RequestDetailImageArtifact {
	return predicate.RequestDetailImageArtifact(sql.NotPredicates(p))
}
