// Code generated by ent, DO NOT EDIT.

package requestdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the requestdetail type in the database.
	Label = "request_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldUpstreamEndpoint holds the string denoting the upstream_endpoint field in the database.
	FieldUpstreamEndpoint = "upstream_endpoint"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldRequestHeaders holds the string denoting the request_headers field in the database.
	FieldRequestHeaders = "request_headers"
	// FieldResponseHeaders holds the string denoting the response_headers field in the database.
	FieldResponseHeaders = "response_headers"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldUpstreamRequestBody holds the string denoting the upstream_request_body field in the database.
	FieldUpstreamRequestBody = "upstream_request_body"
	// FieldResponseContent holds the string denoting the response_content field in the database.
	FieldResponseContent = "response_content"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldResponseTruncated holds the string denoting the response_truncated field in the database.
	FieldResponseTruncated = "response_truncated"
	// Table holds the table name of the requestdetail in the database.
	Table = "request_details"
)

// Columns holds all SQL columns for requestdetail fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldCreatedAt,
	FieldCompletedAt,
	FieldDurationMs,
	FieldStatusCode,
	FieldSuccess,
	FieldPlatform,
	FieldEndpoint,
	FieldUpstreamEndpoint,
	FieldModel,
	FieldUpstreamModel,
	FieldStream,
	FieldUserID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldGroupID,
	FieldSubscriptionID,
	FieldIPAddress,
	FieldUserAgent,
	FieldRequestHeaders,
	FieldResponseHeaders,
	FieldRequestBody,
	FieldUpstreamRequestBody,
	FieldResponseContent,
	FieldResponseBody,
	FieldErrorMessage,
	FieldResponseTruncated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultStatusCode holds the default value on creation for the "status_code" field.
	DefaultStatusCode int
	// DefaultSuccess holds the default value on creation for the "success" field.
	DefaultSuccess bool
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultUpstreamEndpoint holds the default value on creation for the "upstream_endpoint" field.
	DefaultUpstreamEndpoint string
	// UpstreamEndpointValidator is a validator for the "upstream_endpoint" field. It is called by the builders before save.
	UpstreamEndpointValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultUpstreamModel holds the default value on creation for the "upstream_model" field.
	DefaultUpstreamModel string
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultIPAddress holds the default value on creation for the "ip_address" field.
	DefaultIPAddress string
	// IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	IPAddressValidator func(string) error
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
	// DefaultRequestHeaders holds the default value on creation for the "request_headers" field.
	DefaultRequestHeaders map[string][]string
	// DefaultResponseHeaders holds the default value on creation for the "response_headers" field.
	DefaultResponseHeaders map[string][]string
	// DefaultRequestBody holds the default value on creation for the "request_body" field.
	DefaultRequestBody string
	// DefaultUpstreamRequestBody holds the default value on creation for the "upstream_request_body" field.
	DefaultUpstreamRequestBody string
	// DefaultResponseContent holds the default value on creation for the "response_content" field.
	DefaultResponseContent string
	// DefaultResponseBody holds the default value on creation for the "response_body" field.
	DefaultResponseBody string
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultResponseTruncated holds the default value on creation for the "response_truncated" field.
	DefaultResponseTruncated bool
)

// OrderOption defines the ordering options for the RequestDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByUpstreamEndpoint orders the results by the upstream_endpoint field.
func ByUpstreamEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamEndpoint, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByIPAddress orders the results by the ip_address field.
func ByIPAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPAddress, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByRequestBody orders the results by the request_body field.
func ByRequestBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBody, opts...).ToFunc()
}

// ByUpstreamRequestBody orders the results by the upstream_request_body field.
func ByUpstreamRequestBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRequestBody, opts...).ToFunc()
}

// ByResponseContent orders the results by the response_content field.
func ByResponseContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseContent, opts...).ToFunc()
}

// ByResponseBody orders the results by the response_body field.
func ByResponseBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBody, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByResponseTruncated orders the results by the response_truncated field.
func ByResponseTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseTruncated, opts...).ToFunc()
}
