// Code generated by ent, DO NOT EDIT.

package requestdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldRequestID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldCompletedAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldDurationMs, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldStatusCode, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldSuccess, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldPlatform, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldEndpoint, v))
}

// UpstreamEndpoint applies equality check predicate on the "upstream_endpoint" field. It's identical to UpstreamEndpointEQ.
func UpstreamEndpoint(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUpstreamModel, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldStream, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldAPIKeyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldGroupID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldSubscriptionID, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldIPAddress, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUserAgent, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldRequestBody, v))
}

// UpstreamRequestBody applies equality check predicate on the "upstream_request_body" field. It's identical to UpstreamRequestBodyEQ.
func UpstreamRequestBody(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUpstreamRequestBody, v))
}

// ResponseContent applies equality check predicate on the "response_content" field. It's identical to ResponseContentEQ.
func ResponseContent(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldResponseContent, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldResponseBody, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldErrorMessage, v))
}

// ResponseTruncated applies equality check predicate on the "response_truncated" field. It's identical to ResponseTruncatedEQ.
func ResponseTruncated(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldResponseTruncated, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldRequestID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldCompletedAt))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldDurationMs))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldStatusCode, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldSuccess, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldPlatform, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldEndpoint, v))
}

// UpstreamEndpointEQ applies the EQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointNEQ applies the NEQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIn applies the In predicate on the "upstream_endpoint" field.
func UpstreamEndpointIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointNotIn applies the NotIn predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointGT applies the GT predicate on the "upstream_endpoint" field.
func UpstreamEndpointGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointGTE applies the GTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLT applies the LT predicate on the "upstream_endpoint" field.
func UpstreamEndpointLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLTE applies the LTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContains applies the Contains predicate on the "upstream_endpoint" field.
func UpstreamEndpointContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasPrefix applies the HasPrefix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasSuffix applies the HasSuffix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointEqualFold applies the EqualFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContainsFold applies the ContainsFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldUpstreamEndpoint, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldStream, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldUserID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldAPIKeyID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldAccountID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldGroupID))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDIsNil applies the IsNil predicate on the "subscription_id" field.
func SubscriptionIDIsNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIsNull(FieldSubscriptionID))
}

// SubscriptionIDNotNil applies the NotNil predicate on the "subscription_id" field.
func SubscriptionIDNotNil() predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotNull(FieldSubscriptionID))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldIPAddress, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldUserAgent, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldRequestBody, v))
}

// UpstreamRequestBodyEQ applies the EQ predicate on the "upstream_request_body" field.
func UpstreamRequestBodyEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyNEQ applies the NEQ predicate on the "upstream_request_body" field.
func UpstreamRequestBodyNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyIn applies the In predicate on the "upstream_request_body" field.
func UpstreamRequestBodyIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldUpstreamRequestBody, vs...))
}

// UpstreamRequestBodyNotIn applies the NotIn predicate on the "upstream_request_body" field.
func UpstreamRequestBodyNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldUpstreamRequestBody, vs...))
}

// UpstreamRequestBodyGT applies the GT predicate on the "upstream_request_body" field.
func UpstreamRequestBodyGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyGTE applies the GTE predicate on the "upstream_request_body" field.
func UpstreamRequestBodyGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyLT applies the LT predicate on the "upstream_request_body" field.
func UpstreamRequestBodyLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyLTE applies the LTE predicate on the "upstream_request_body" field.
func UpstreamRequestBodyLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyContains applies the Contains predicate on the "upstream_request_body" field.
func UpstreamRequestBodyContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyHasPrefix applies the HasPrefix predicate on the "upstream_request_body" field.
func UpstreamRequestBodyHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyHasSuffix applies the HasSuffix predicate on the "upstream_request_body" field.
func UpstreamRequestBodyHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyEqualFold applies the EqualFold predicate on the "upstream_request_body" field.
func UpstreamRequestBodyEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyContainsFold applies the ContainsFold predicate on the "upstream_request_body" field.
func UpstreamRequestBodyContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldUpstreamRequestBody, v))
}

// ResponseContentEQ applies the EQ predicate on the "response_content" field.
func ResponseContentEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldResponseContent, v))
}

// ResponseContentNEQ applies the NEQ predicate on the "response_content" field.
func ResponseContentNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldResponseContent, v))
}

// ResponseContentIn applies the In predicate on the "response_content" field.
func ResponseContentIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldResponseContent, vs...))
}

// ResponseContentNotIn applies the NotIn predicate on the "response_content" field.
func ResponseContentNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldResponseContent, vs...))
}

// ResponseContentGT applies the GT predicate on the "response_content" field.
func ResponseContentGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldResponseContent, v))
}

// ResponseContentGTE applies the GTE predicate on the "response_content" field.
func ResponseContentGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldResponseContent, v))
}

// ResponseContentLT applies the LT predicate on the "response_content" field.
func ResponseContentLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldResponseContent, v))
}

// ResponseContentLTE applies the LTE predicate on the "response_content" field.
func ResponseContentLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldResponseContent, v))
}

// ResponseContentContains applies the Contains predicate on the "response_content" field.
func ResponseContentContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldResponseContent, v))
}

// ResponseContentHasPrefix applies the HasPrefix predicate on the "response_content" field.
func ResponseContentHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldResponseContent, v))
}

// ResponseContentHasSuffix applies the HasSuffix predicate on the "response_content" field.
func ResponseContentHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldResponseContent, v))
}

// ResponseContentEqualFold applies the EqualFold predicate on the "response_content" field.
func ResponseContentEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldResponseContent, v))
}

// ResponseContentContainsFold applies the ContainsFold predicate on the "response_content" field.
func ResponseContentContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldResponseContent, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldResponseBody, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ResponseTruncatedEQ applies the EQ predicate on the "response_truncated" field.
func ResponseTruncatedEQ(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldEQ(FieldResponseTruncated, v))
}

// ResponseTruncatedNEQ applies the NEQ predicate on the "response_truncated" field.
func ResponseTruncatedNEQ(v bool) predicate.RequestDetail {
	return predicate.RequestDetail(sql.FieldNEQ(FieldResponseTruncated, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestDetail) predicate.RequestDetail {
	return predicate.RequestDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestDetail) predicate.RequestDetail {
	return predicate.RequestDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestDetail) predicate.RequestDetail {
	return predicate.RequestDetail(sql.NotPredicates(p))
}
